### ISSUE TITLE
Advice on how to integrate `entry.server.tsx` with Chakra UI

### ISSUE THREAD

**Issue by JackEdwardLyons** [dev-xo/barebones-stack#9]
Hi there,

Love the stack, thanks for creating it! I'm looking to integrate it with Chakra UI but not sure how to configure the `entry.server.tsx` file. The [Chakra UI Docs](https://chakra-ui.com/getting-started/remix-guide) have a how-to guide but the `entry.server.tsx` file is completely different to your configuration. I've managed to follow the other parts and get it working which is great, but just not sure how to proceed with the server file.

Any help on how to integrate it would be much appreciated. Thank you!

**Comment by dev-xo** [comment]
Hello @JackEdwardLyons thanks you for reaching on here! If im not wrong the `entry.server.tsx` file is the same as the main Indie Stack and Blues Stack.

Sadly Im not into Chakra UI yet, but I think you have to extend the configuration of Remix App Server. I think there is a command for that, that ejects the express server file. (Check Remix Docs, maybe you can find it or ask on the Remix Discord Server)

Also Check this [Link](https://github.com/remix-run/remix/pull/4123)
Seems like someone is able to update the Express Server file without ejecting.

Hope I helped you a bit!
